services:
  postgres:
    image: postgres:18
    container_name: secure-media-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: secure_media
      POSTGRES_USER: secure_media
      POSTGRES_PASSWORD: secure_media_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
  media-worker:
    image: secure-media-worker:local
    container_name: secure-media-worker
    restart: unless-stopped
    stop_signal: SIGTERM
    stop_grace_period: 60s
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: "5432"
      DB_NAME: secure_media
      DB_USER: secure_media
      DB_PASSWORD: secure_media_password
      AWS_PROFILE: personal
      AWS_REGION: ap-southeast-2
      AWS_SHARED_CREDENTIALS_FILE: /home/node/.aws/credentials
      AWS_CONFIG_FILE: /home/node/.aws/config
      MEDIA_BUCKET_NAME: secure-proximity-media-dev-sharing-001
    volumes:
      - ${HOME}/.aws:/home/node/.aws:ro
  redis:
    image: redis:8
    container_name: secure-media-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:

# 88281dfda3df32295fab1a30bd071a7a9845323f2b1aff8005cdd1c0319b9983
